services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - db_network
      
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    mem_limit: 1024m
    cpus: "0.5"
    networks:
      - db_network
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks: 
      - default
      
  # http://localhost:5984/_utils/# 
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    ports:
      - '5984:5984'
    restart: unless-stopped
    volumes:
      - ./couchdb_data:/opt/couchdb/etc/local.d -d couchdb
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: secret
    networks:
      - db_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - db_network

  # http://localhost:8080
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks: 
      - default
  
  # http://localhost:9000
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - '8181:8000'
      - '9000:9000'
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - db_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    networks:
      - db_network
      
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '8282:80'
    restart: unless-stopped
    environment: 
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
    networks:
      - db_network

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  couchdb_data:
    driver: local
  portainer_data:
    driver: local

networks:
  db_network: {}
